Dev saule
SunMadeteam/Frontend pull request #10
Opened 2022-02-18 05:58 UTC by oichievas

2022-02-18 06:17 UTC, ChpokmanKG requested changes

2022-02-18 06:17 UTC, ChpokmanKG commented on src/common/components/Input-code/index.jsx
> +    if (e.keyCode === 8 && !code[slot] && slot !== 0) {
const KEYS_CODE = {
    BACKSPACE: 8
}
Вынеси код кнопки в объект

2022-02-18 06:17 UTC, ChpokmanKG commented on src/common/components/Input-code/index.jsx
> +  const onKeyUp = (e, slot) => {
Проверь, это работает на телефонах

2022-02-18 06:17 UTC, ChpokmanKG commented on src/features/Registration-confirmation-code/index.scss
> +// CSS Inputs Styles
Можешь удалить

2022-02-18 06:17 UTC, ChpokmanKG commented on src/features/Registration-confirmation-code/index.jsx
> +          setTimeout(() => setLoading(false), 10000);
добавь clearTimeout()

2022-03-15 20:50 UTC, closed without merging

2022-03-15 20:50 UTC, SunMadeteam commented
Fixed comments